"""initial schema

Revision ID: ada9b66599a5
Revises: 
Create Date: 2025-10-09 10:17:33.236954

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ada9b66599a5'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_is_pending', 'random_boolean_function_trials', ['job_id', 'counts', 'is_failed'], unique=False)
    op.create_index(op.f('ix_random_boolean_function_trials_compiler_name'), 'random_boolean_function_trials', ['compiler_name'], unique=False)
    op.create_index(op.f('ix_random_boolean_function_trials_job_id'), 'random_boolean_function_trials', ['job_id'], unique=False)
    op.create_index(op.f('ix_random_boolean_function_trials_problem_id'), 'random_boolean_function_trials', ['problem_id'], unique=False)
    op.create_index('ix_num_vars_complexity', 'random_boolean_functions', ['num_vars', 'complexity'], unique=False)
    op.drop_column('random_boolean_functions', 'problem_type')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('random_boolean_functions', sa.Column('problem_type', sa.VARCHAR(length=128), nullable=True))
    op.drop_index('ix_num_vars_complexity', table_name='random_boolean_functions')
    op.drop_index(op.f('ix_random_boolean_function_trials_problem_id'), table_name='random_boolean_function_trials')
    op.drop_index(op.f('ix_random_boolean_function_trials_job_id'), table_name='random_boolean_function_trials')
    op.drop_index(op.f('ix_random_boolean_function_trials_compiler_name'), table_name='random_boolean_function_trials')
    op.drop_index('ix_is_pending', table_name='random_boolean_function_trials')
    # ### end Alembic commands ###
