"""Change is_pending index

Revision ID: c363abadef8f
Revises: f6c60ba20c99
Create Date: 2025-11-01 09:42:04.500326

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c363abadef8f'
down_revision: Union[str, Sequence[str], None] = 'f6c60ba20c99'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_is_pending'), table_name='random_boolean_function_trials')
    op.create_index('ix_is_pending', 'random_boolean_function_trials', ['job_id'], unique=False, sqlite_where=sa.text('counts IS NULL AND is_failed = 0'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_is_pending', table_name='random_boolean_function_trials', sqlite_where=sa.text('counts IS NULL AND is_failed = 0'))
    op.create_index(op.f('ix_is_pending'), 'random_boolean_function_trials', ['job_id', 'counts', 'is_failed'], unique=False)
    # ### end Alembic commands ###
