"""Add backend properties table

Revision ID: e7d3171c555f
Revises: fc2ae09326d9
Create Date: 2025-10-27 19:39:37.457436

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e7d3171c555f'
down_revision: Union[str, Sequence[str], None] = 'fc2ae09326d9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('backend_properties',
    sa.Column('backend_name', sa.String(), nullable=False),
    sa.Column('last_update_date', sa.DateTime(), nullable=False),
    sa.Column('gates_data', sa.JSON(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('backend_name', 'last_update_date', name='uq_backend_name_last_update')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('backend_properties')
    # ### end Alembic commands ###
