"""Add pretranspiled circuit column

Revision ID: f6c60ba20c99
Revises: e7d3171c555f
Create Date: 2025-10-28 22:07:17.597370

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f6c60ba20c99'
down_revision: Union[str, Sequence[str], None] = 'e7d3171c555f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('random_boolean_function_trials', sa.Column('_circuit_pretranspile_qpy', sa.LargeBinary(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('random_boolean_function_trials', '_circuit_pretranspile_qpy')
    # ### end Alembic commands ###
