"""Add circuit metrics

Revision ID: fc2ae09326d9
Revises: ada9b66599a5
Create Date: 2025-10-14 22:28:26.764096

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fc2ae09326d9'
down_revision: Union[str, Sequence[str], None] = 'ada9b66599a5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('random_boolean_function_trials', sa.Column('circuit_depth', sa.Integer(), nullable=True))
    op.add_column('random_boolean_function_trials', sa.Column('circuit_op_counts', sa.JSON(), nullable=True))
    op.add_column('random_boolean_function_trials', sa.Column('circuit_num_single_qubit_gates', sa.Integer(), nullable=True))
    op.add_column('random_boolean_function_trials', sa.Column('circuit_num_gates', sa.Integer(), nullable=True))
    op.add_column('random_boolean_function_trials', sa.Column('circuit_num_qubits', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('random_boolean_function_trials', 'circuit_num_qubits')
    op.drop_column('random_boolean_function_trials', 'circuit_num_gates')
    op.drop_column('random_boolean_function_trials', 'circuit_num_single_qubit_gates')
    op.drop_column('random_boolean_function_trials', 'circuit_op_counts')
    op.drop_column('random_boolean_function_trials', 'circuit_depth')
    # ### end Alembic commands ###
