"""Change pass manager config

Revision ID: 1b1b68115a2c
Revises: 9a88428a93f6
Create Date: 2025-12-02 23:33:03.425039

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = '1b1b68115a2c'
down_revision: Union[str, Sequence[str], None] = '9a88428a93f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pipeline_configs', sa.Column('pass_manager_factory_name', sa.String(), nullable=True))
    op.add_column('pipeline_configs', sa.Column('pass_manager_kwargs', sa.JSON(), nullable=False))
    op.drop_column('pipeline_configs', 'pass_manager_config')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pipeline_configs', sa.Column('pass_manager_config', sqlite.JSON(), nullable=False))
    op.drop_column('pipeline_configs', 'pass_manager_kwargs')
    op.drop_column('pipeline_configs', 'pass_manager_factory_name')
    # ### end Alembic commands ###
