"""Add CliqueOracleTrial

Revision ID: 55e64ee84a59
Revises: 1b1b68115a2c
Create Date: 2025-12-16 12:23:43.631717

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '55e64ee84a59'
down_revision: Union[str, Sequence[str], None] = '1b1b68115a2c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_clique_oracle_trials_is_pending', 'clique_oracle_trials', ['job_id'], unique=False, sqlite_where=sa.text('counts IS NULL AND is_failed = 0'))
    op.drop_index(op.f('ix_is_pending'), table_name='clique_trials', sqlite_where=sa.text('counts IS NULL AND is_failed = 0'))
    op.create_index('ix_clique_trials_is_pending', 'clique_trials', ['job_id'], unique=False, sqlite_where=sa.text('counts IS NULL AND is_failed = 0'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_clique_trials_is_pending', table_name='clique_trials', sqlite_where=sa.text('counts IS NULL AND is_failed = 0'))
    op.create_index(op.f('ix_is_pending'), 'clique_trials', ['job_id'], unique=False, sqlite_where=sa.text('counts IS NULL AND is_failed = 0'))
    op.drop_index('ix_clique_oracle_trials_is_pending', table_name='clique_oracle_trials', sqlite_where=sa.text('counts IS NULL AND is_failed = 0'))
    # ### end Alembic commands ###
