"""Save pipeline config

Revision ID: 9a88428a93f6
Revises: db6155d4d991
Create Date: 2025-12-02 13:43:23.458466

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9a88428a93f6'
down_revision: Union[str, Sequence[str], None] = 'db6155d4d991'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pipeline_configs',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('synthesizer_config', sa.JSON(), nullable=False),
    sa.Column('compiler_config', sa.JSON(), nullable=False),
    sa.Column('pass_manager_config', sa.JSON(), nullable=False),
    sa.Column('backend_name', sa.String(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pipeline_configs_name'), 'pipeline_configs', ['name'], unique=True)
    
    # to add the foreign key to clique_trials, we need to use batch_alter_table due to SQLite limitations
    with op.batch_alter_table('clique_trials', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column('pipeline_config_id', sa.Integer(), nullable=True)
        )
        batch_op.create_foreign_key(
            'fk_clique_pipeline_config',  # Constraint name
            'pipeline_configs',           # Referenced table
            ['pipeline_config_id'],       # Column in 'clique_trials'
            ['id']                        # Column in 'pipeline_configs'
        )
        
        batch_op.create_index(
            op.f('ix_clique_trials_pipeline_config_id'),
            ['pipeline_config_id'],
            unique=False
        )
        batch_op.drop_index(op.f('ix_is_pending'))
        batch_op.create_index(
            'ix_is_pending', 
            ['job_id'], 
            unique=False, 
            sqlite_where=sa.text('counts IS NULL AND is_failed = 0')
        )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clique_trials', schema=None) as batch_op:
        batch_op.drop_index(op.f('ix_clique_trials_pipeline_config_id'))
        batch_op.drop_constraint('fk_clique_pipeline_config', type_='foreignkey')
        batch_op.drop_column('pipeline_config_id')
        batch_op.drop_index('ix_is_pending')
        batch_op.create_index(op.f('ix_is_pending'), ['job_id'], unique=False) # Revert to simple index
    op.drop_table('pipeline_configs')
    # ### end Alembic commands ###
