"""Add pretranspiled circuit column

Revision ID: db6155d4d991
Revises: 
Create Date: 2025-10-28 22:25:43.208705

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'db6155d4d991'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clique_trials', sa.Column('_circuit_pretranspile_qpy', sa.LargeBinary(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('clique_trials', '_circuit_pretranspile_qpy')
    # ### end Alembic commands ###
